## 测试我们的算法

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y = iris.target

In [6]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

## train_test_split

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
shuffle_indexes = np.random.permutation(len(X))

In [10]:
shuffle_indexes

array([ 84,  91,  52, 140,  31,  77,  47, 114,  42, 107,  75,  81, 143,
        48,  58, 139, 106,  50, 104, 129,  99, 146, 136, 135,  57, 108,
        88,  85, 122,  29, 125,   1, 137,  22, 131,  46, 134, 103,  62,
       126,  56,  80, 119, 121, 124,  90,  39, 109,   7,  70,  78,  12,
        93,  79,  23,  89, 111, 105, 132, 102,  98, 118,  25,  20,  73,
       115, 148,   9,  44, 133, 147,   4,  54,  15,  96, 149,  95, 120,
        82,   3,  72,  36,  24,  66,  71, 141,  19,  94, 112,  65,  26,
        87,  40,  43,  34, 144, 142,  45,  38,  30,  35,  17,   5,   0,
        69,  76, 145, 116,   2,  41, 128,  59,  67,  92, 130,  13,  83,
       100,  74, 127,  28, 113,   6,  53,  33,  11,  61, 110,  10,  60,
        68, 101,  21,  86,  64, 138,   8,  63,  14,  27,  37,  32,  51,
        97,  49,  16, 123, 117,  55,  18])

In [11]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)

In [12]:
test_size

30

In [13]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [14]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


## 使用我们的算法

In [45]:
from playML.model_selection import train_test_split

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [47]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [48]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [55]:
from playML.knn import KNNClassifier

In [56]:
my_knn_clf = KNNClassifier(k=3)

In [57]:
my_knn_clf.fit(X_train,y_train)

In [58]:
y_predict = my_knn_clf.predict(X_test)

In [60]:
y_predict = np.array(y_predict)

In [61]:
y_predict

array([2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 2, 2,
       2, 1, 2, 2, 1, 2, 1, 1])

In [62]:
y_test

array([2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 2,
       2, 1, 2, 2, 1, 2, 1, 1])

In [63]:
np.sum(y_test == y_predict)

29

In [64]:
np.sum(y_test == y_predict) / len(y_test)

0.9666666666666667

## sklearn中的train_test_split

In [65]:
from sklearn.model_selection import train_test_split

In [72]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)

In [73]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [74]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
