In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [3]:
%run knn_function/knn.py

In [4]:
predirect_y = kNN_classify(6,X_train,y_train,x)

In [5]:
predirect_y

1

## 使用scikit-learn中的KNN

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn_classifier = KNeighborsClassifier(n_neighbors=6)

In [8]:
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [11]:
knn_classifier.predict(x.reshape(1,-1))

array([1])

In [12]:
y_predirect = knn_classifier.predict(x.reshape(1,-1))

In [13]:
y_predirect

array([1])

In [14]:
y_predirect[0]

1

## 重新整理我们的KNN代码

In [25]:
%run knn/knn.py

In [26]:
knn_clf = KNNClassifier(k=6)

In [27]:
knn_clf.fit(X_train,y_train)

In [28]:
X_predirect = x.reshape(1,-1)
y_predirect = knn_clf.predict(X_predirect)

In [29]:
X_predirect

array([[8.09360732, 3.36573151]])

In [30]:
y_predirect

[1]

In [31]:
y_predirect[0]

1

In [36]:
for x in X_train:
    print(x)

[3.39353321 2.33127338]
[3.11007348 1.78153964]
[1.34380883 3.36836095]
[3.58229404 4.67917911]
[2.28036244 2.86699026]
[7.42343694 4.69652288]
[5.745052  3.5339898]
[9.17216862 2.51110105]
[7.79278348 3.42408894]
[7.93982082 0.79163723]
