# 03 numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.3'

## Python List 的特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [6]:
L[5] = 'Machine Learning'
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [7]:
import array

In [8]:
arr = array.array('i',[i for i in range(10)])

In [9]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5] = 100

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [13]:
arr[5] = 'Machine Learning'

TypeError: an integer is required (got type str)

## numpy.array

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]

5

In [16]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [17]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [18]:
nparr.dtype

dtype('int64')

In [19]:
nparr[5] = 5.0

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr.dtype

dtype('int64')

In [22]:
nparr[3] = 100.14 # 隐式类型转换

In [23]:
nparr

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [24]:
nparr.dtype

dtype('int64')

In [25]:
nparr2 = np.array([1,2,3.0])

In [26]:
nparr2.dtype

dtype('float64')