## 聚合操作

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.04093159, 0.87223363, 0.33585273, 0.35034145, 0.17508881,
       0.24475493, 0.39087649, 0.60031877, 0.54570472, 0.25201602,
       0.78183755, 0.42551674, 0.30908736, 0.97769237, 0.11831867,
       0.14839848, 0.43379233, 0.95902539, 0.99737391, 0.22427714,
       0.50325938, 0.06281513, 0.64506277, 0.5454767 , 0.74884855,
       0.78088203, 0.4536101 , 0.12436004, 0.41373006, 0.69867041,
       0.72618579, 0.52131826, 0.69923821, 0.62842531, 0.33086822,
       0.06547235, 0.55130801, 0.43995746, 0.27621668, 0.96041437,
       0.56640483, 0.51922095, 0.31031302, 0.61723217, 0.87648852,
       0.38307857, 0.74572448, 0.94123711, 0.6641645 , 0.30342209,
       0.90244534, 0.17019528, 0.10164372, 0.84828684, 0.16141123,
       0.89149039, 0.81442399, 0.32557744, 0.55537033, 0.18878295,
       0.10540093, 0.24708413, 0.92823425, 0.07145867, 0.59256   ,
       0.02732306, 0.5379088 , 0.16884112, 0.82949502, 0.38535053,
       0.71756234, 0.49308074, 0.15689876, 0.18929722, 0.64923

In [3]:
sum(L)

49.285055458484614

In [4]:
np.sum(L)

49.285055458484635

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

73.3 ms ± 607 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
354 µs ± 5.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
np.min(big_array)

7.022572794390669e-07

In [9]:
np.max(big_array)

0.9999982736879477

In [10]:
big_array.min()

7.022572794390669e-07

In [11]:
big_array.max()

0.9999982736879477

In [12]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X)

120

In [14]:
np.sum(X,axis=0) # 沿着行的方向运算，即每一列的和

array([24, 28, 32, 36])

In [15]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [16]:
np.prod(X)

0

In [17]:
np.prod(X + 1)

20922789888000

In [18]:
np.mean(X) # 平均值

7.5

In [19]:
np.median(X) # 中位数

7.5

In [20]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array,q=50) # 百分位

0.49935172477438095

In [23]:
np.median(big_array)

0.49935172477438095

In [24]:
np.max(big_array)

0.9999982736879477

In [25]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

7.022572794390669e-07
0.24933945816302125
0.49935172477438095
0.7500627637513362
0.9999982736879477


In [26]:
np.var(big_array) # 方差

0.08344367014617102

In [27]:
np.std(big_array) # 标准差

0.2888661803433746

In [28]:
x = np.random.normal(0,1,size=1000000)

In [29]:
np.mean(x)

-0.001381965554704974

In [30]:
np.std(x)

0.9994489854995655