## 索引

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0,1,size=1000000)

In [3]:
np.min(x)

-5.279226140015301

In [5]:
np.argmin(x) # 最小值的索引

643041

In [7]:
x[643041]

-5.279226140015301

In [8]:
np.argmax(x)

112024

In [9]:
x[112024]

4.946163762639714

In [10]:
np.max(x)

4.946163762639714

## 排序和使用索引

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)
x

array([ 7, 13, 12,  5, 11,  4,  6, 10,  0, 14, 15,  2,  8,  9,  1,  3])

In [13]:
np.sort(x) # 不影响x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x

array([ 7, 13, 12,  5, 11,  4,  6, 10,  0, 14, 15,  2,  8,  9,  1,  3])

In [15]:
x.sort()

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10,size=(4,4))
X

array([[0, 1, 8, 0],
       [5, 6, 4, 9],
       [4, 3, 3, 5],
       [2, 7, 5, 0]])

In [19]:
np.sort(X)

array([[0, 0, 1, 8],
       [4, 5, 6, 9],
       [3, 3, 4, 5],
       [0, 2, 5, 7]])

In [20]:
np.sort(X,axis=1)

array([[0, 0, 1, 8],
       [4, 5, 6, 9],
       [3, 3, 4, 5],
       [0, 2, 5, 7]])

In [21]:
np.sort(X,axis=0)

array([[0, 1, 3, 0],
       [2, 3, 4, 0],
       [4, 6, 5, 5],
       [5, 7, 8, 9]])

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.random.shuffle(x)

In [24]:
x

array([10, 15,  6,  0,  2,  9,  8,  7,  5, 11,  4,  1,  3, 14, 12, 13])

In [25]:
np.argsort(x)

array([ 3, 11,  4, 12, 10,  8,  2,  7,  6,  5,  0,  9, 14, 15, 13,  1])

In [26]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9,  8, 10, 11, 15, 14, 12, 13])

In [27]:
np.argpartition(x,3)

array([ 3, 11,  4, 12, 10,  8,  2,  7,  5,  6,  0,  9,  1, 13, 14, 15])

In [28]:
X

array([[0, 1, 8, 0],
       [5, 6, 4, 9],
       [4, 3, 3, 5],
       [2, 7, 5, 0]])

In [29]:
np.argsort(X,axis=1)

array([[0, 3, 1, 2],
       [2, 0, 1, 3],
       [1, 2, 0, 3],
       [3, 0, 2, 1]])

In [30]:
np.argsort(X,axis=0)

array([[0, 0, 2, 0],
       [3, 2, 1, 3],
       [2, 1, 3, 2],
       [1, 3, 0, 1]])

In [31]:
np.argpartition(X,2,axis=1)

array([[0, 3, 1, 2],
       [2, 0, 1, 3],
       [1, 2, 0, 3],
       [3, 0, 2, 1]])