In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [6]:
ind = [3,5,8]

In [7]:
x[ind] # fancy indexing

array([3, 5, 8])

In [8]:
ind = np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [12]:
X[0,col]

array([1, 2, 3])

In [13]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
col = [True,False,True,True] # 使用布尔数组

In [15]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 中的比较

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [19]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [22]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
np.sum(x <= 3) # True 1 False 0

4

In [27]:
np.count_nonzero(x <= 3)

4

In [28]:
np.any(x == 0) # 存在一个为true，返回true

True

In [29]:
np.any(x < 0)

False

In [30]:
np.all(x == 0) # 全都为true，返回true

False

In [31]:
np.all(x >= 0)

True

In [32]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.sum(X % 2 == 0)

8

In [34]:
np.sum(X % 2 == 0,axis=1)

array([2, 2, 2, 2])

In [35]:
np.sum(X % 2 == 0,axis=0)

array([4, 0, 4, 0])

In [36]:
np.all(X > 0,axis=1)

array([False,  True,  True,  True])

In [37]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
np.sum((x > 3) & (x < 10)) # 位运算

6

In [39]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-39-d834f65999a2>, line 1)

In [41]:
np.sum((x > 3) and (x < 10))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
np.sum((x % 2 == 0) | (x > 10))

11

In [44]:
np.sum(~(x == 0)) # 非运算

15

In [45]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [46]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [52]:
X[X[:,3] % 3 == 0,-1]

array([ 3, 15])

## Pandas